version: '3.9'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    restart: unless-stopped

    ports:
      - '5433:5432' # aman dari konflik PostgreSQL lokal

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: semantic_search_db

    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgvector_data:
